### ISSUE TITLE
Regarding TLGAN

### ISSUE THREAD

**Issue by seekingdeep** [SYR-Aegis/BrailleOCR#22]
@eddie94 @SHINJUNGWOO Hi there,

1) When using a U-Net generator, did you solve the vanishing gradients and mode collapse issues?
2) When using a U-Net generator, can we remove the ROI proposal step?
3) TLGAN have 1.45M parameters, but what is the FLOPS count?

**Comment by eddie94** [comment]
1. We did not use U-Net for the generator. TLGAN follows the work of SRGAN which is a model for super resolution
2. TLGAN uses a GAN model for predicting the ROI given the raw image i.e. the original image that contains text
3. Unfortunately we didn't measure the FLOPs when we were building this project.
though, I think it's a simplified version of SRGAN so please refer to the original work.

**Comment by SHINJUNGWOO** [comment]
1. When using U-net gernerator, I think using Wasserstein loss and Interpolation loss method for solve the vanishing gradients and mde collaspe
2. I think so,. but, this propoesed network TLGAN is very practical model,

**Comment by seekingdeep** [comment]
@eddie94 @SHINJUNGWOO **Last questions,**

4) Will the full implementation of TLGAN be released to the community.
5) Is the predicted text localization map a Cylindrical Gaussian "blue" or a Baseline "red"?

![image](https://user-images.githubusercontent.com/71519088/122539737-97e05080-d030-11eb-9329-9da732f97f58.png)

![image](https://user-images.githubusercontent.com/71519088/122539836-b6dee280-d030-11eb-83df-fe2813ffb4c6.png)

**Comment by SHINJUNGWOO** [comment]
4.  Umm...we are not author of TLgan, but I think very positive to release of our code in community
5.  Output of our model is  Cylindrical Gaussian, so that, in code, you can find Cylindrical Gaussian to axis

**Comment by eddie94** [comment]
The color does not matter and the size of the gaussian map depends on the size of text
Both images you sent us are gaussian cylindrical maps, however the blue one is the ground truth and the red one is the prediction of TLGAN.
Therefore I guess the answer to your question must be the red one since you have asked for the "prediction" of the model.

**Comment by seekingdeep** [comment]
thanks
