### ISSUE TITLE
tlgan_train.py 관련 issue

### ISSUE THREAD

**Issue by PrimeOfMine** [SYR-Aegis/BrailleOCR#23]
안녕하세요 tlgan_train.py 에서 한가지 문의 사항이 있어서 이슈 남깁니다.

tlgan_train.py 에서 1 mini-batch size = 8 default 로 잡혀있는데 , 실제 train 코드 상에서 1epoch 에서 1 full batch 가 학습이 되는 것인지 의문이 듭니다. 제가 확인하기에는 1epoch 에서 1 mini-batch 혹은 1 img 만 학습이 되는 것 같습니다.

**Comment by eddie94** [comment]
코드 확인 결과 한 epoch당 하나의 미니배치가 학습에 이용된다는 사실을 발견했습니다
아래 커밋 내용을 확인해 주세요
https://github.com/SYR-Aegis/BrailleOCR/commit/e1bb8a55e8c3c051e9d116988cb6fe50ab0005cb

버그 제보해주셔서 감사드립니다

**Comment by PrimeOfMine** [comment]
해결 되었습니다.

감사합니다.
